name: learn_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rate_my_app:
  flutter_widget_from_html:
  share_plus:
  get:
  flutter_svg:
  shared_preferences:
  pin_input_text_field:
  curved_navigation_bar:
  carousel_slider:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/AppLogo.png"