name: learn_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  flutter_svg:
  shared_preferences:
  pin_input_text_field:
  curved_navigation_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svg/